import React from "react";
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  Platform,
} from "react-native";
import { Link } from "expo-router";

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <Text style={styles.p}>{children}</Text>;
}

function Li({ children }: { children: React.ReactNode }) {
  return (
    <View style={styles.li}>
      <Text style={styles.bullet}>•</Text>
      <Text style={styles.liText}>{children}</Text>
    </View>
  );
}

export default function TermsPage() {
  if (Platform.OS !== "web") return null;

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <Text style={styles.headerSub}>Anchor Bible App</Text>
      </View>

      <View style={styles.content}>
        <Link href="/(marketing)" asChild>
          <TouchableOpacity style={styles.backLink}>
            <Text style={styles.backLinkText}>← Back to Anchor</Text>
          </TouchableOpacity>
        </Link>

        <View style={styles.updated}>
          <Text style={styles.updatedText}>Last Updated: January 29, 2026</Text>
        </View>

        <Section title="1. Agreement to Terms">
          <P>
            Welcome to Anchor ("we," "our," or "us"). These Terms of Service
            ("Terms") govern your access to and use of the Anchor mobile
            application (the "App") and related services.
          </P>
          <P>
            By downloading, installing, or using the App, you agree to be bound
            by these Terms. If you do not agree, do not use the App.
          </P>
        </Section>

        <Section title="2. Description of Service">
          <P>Anchor is a Bible reading and study application that provides:</P>
          <Li>Bible Reading: Access to multiple Bible translations</Li>
          <Li>
            Verse of the Day: Daily inspirational verses with themed rotation
          </Li>
          <Li>AI Chat Assistant: Bible study assistance powered by AI</Li>
          <Li>Reading Progress: Track completed chapters and history</Li>
          <Li>Bookmarks & Favorites: Save and organize Bible verses</Li>
          <Li>Verse Sharing: Create and share custom verse images</Li>
          <Li>Audio Bible: Listen to chapters read aloud</Li>
        </Section>

        <Section title="3. Eligibility">
          <Li>The App is available to users of all ages</Li>
          <Li>Users under 13 require parental or guardian consent</Li>
          <Li>
            You must provide accurate information when creating an account
          </Li>
          <Li>You are responsible for maintaining account security</Li>
        </Section>

        <Section title="4. User Accounts">
          <P>
            You must create an account to access certain features. One account
            per person. You are responsible for all activity on your account.
            You may delete your account at any time through App settings. We
            reserve the right to suspend accounts that violate these Terms.
          </P>
        </Section>

        <Section title="5. Subscription Plans">
          <Li>Weekly Plan: $3.99 per week</Li>
          <Li>Monthly Plan: $12.99 per month</Li>
          <Li>Yearly Plan: $79.99 per year</Li>
          <P>
            Subscriptions auto-renew unless cancelled 24 hours before the end of
            the current period. Manage subscriptions in your device's Account
            Settings.
          </P>
        </Section>

        <Section title="6. AI Chat Feature">
          <P>
            The AI Chat feature helps you understand Bible passages, get answers
            to theological questions, and receive study guidance.
          </P>
          <Li>Free users: 10 AI messages per day</Li>
          <Li>Subscribers: 100 AI messages per day</Li>
          <P>
            AI responses are generated by artificial intelligence and may not
            always be accurate. They are for informational purposes only, not
            professional theological advice.
          </P>
        </Section>

        <Section title="7. User Conduct">
          <P>You agree NOT to:</P>
          <Li>Use the App for any illegal purpose</Li>
          <Li>Harass, abuse, or harm others</Li>
          <Li>Attempt to hack or compromise the App's security</Li>
          <Li>Scrape or extract data from the App</Li>
          <Li>Abuse AI features or bypass rate limits</Li>
        </Section>

        <Section title="8. Intellectual Property">
          <P>
            Bible translations are provided by third-party publishers, each
            subject to their own licensing. The App itself, including design,
            code, and branding, is owned by Anchor and protected by intellectual
            property laws.
          </P>
        </Section>

        <Section title="9. Disclaimers">
          <P>
            THE APP IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. We are
            not liable for indirect, incidental, or consequential damages. Our
            total liability will not exceed the amount you paid in the past 12
            months.
          </P>
        </Section>

        <Section title="10. Governing Law">
          <P>
            These Terms are governed by the laws of the State of South Carolina,
            United States. Disputes will be resolved through binding
            arbitration. You agree to resolve disputes individually, not as part
            of a class action.
          </P>
        </Section>

        <Section title="11. Changes to Terms">
          <P>
            We may update these Terms periodically. Continued use after changes
            constitutes acceptance. We will notify you of material changes via
            the App.
          </P>
        </Section>

        <Section title="12. Contact">
          <P>Email: Anchrapp@outlook.com</P>
          <P>Website: anchrapp.io</P>
        </Section>

        <View style={styles.notice}>
          <Text style={styles.noticeText}>
            BY USING THE ANCHOR APP, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE
            TERMS OF SERVICE, UNDERSTAND THEM, AND AGREE TO BE BOUND BY THEM.
          </Text>
        </View>

        <View style={styles.footerInfo}>
          <Text style={styles.footerInfoText}>
            Effective Date: January 29, 2026
          </Text>
        </View>
      </View>

      <View style={styles.footer}>
        <Text style={styles.copyright}>
          © 2026 Anchor Bible App. All rights reserved.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8f9fa" },
  header: {
    backgroundColor: "#000000",
    padding: 48,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 40,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 8,
  },
  headerSub: { fontSize: 18, color: "#9ca3af" },
  content: {
    maxWidth: 900,
    alignSelf: "center",
    width: "100%",
    padding: 32,
    backgroundColor: "#ffffff",
  },
  backLink: {
    backgroundColor: "#1a1a1a",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    alignSelf: "flex-start",
    marginBottom: 24,
  },
  backLinkText: { color: "#ffffff", fontWeight: "600" },
  updated: {
    backgroundColor: "#f7fafc",
    borderLeftWidth: 4,
    borderLeftColor: "#1a1a1a",
    padding: 16,
    marginBottom: 32,
  },
  updatedText: { fontWeight: "600", color: "#4a5568" },
  section: { marginBottom: 32 },
  sectionTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#2d3748",
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: "#e2e8f0",
  },
  p: { fontSize: 16, color: "#4a5568", lineHeight: 26, marginBottom: 12 },
  li: { flexDirection: "row", marginBottom: 8, paddingLeft: 8 },
  bullet: { color: "#4a5568", marginRight: 8, fontSize: 16 },
  liText: { flex: 1, fontSize: 16, color: "#4a5568", lineHeight: 24 },
  notice: {
    backgroundColor: "#fff3cd",
    borderLeftWidth: 4,
    borderLeftColor: "#ffc107",
    padding: 16,
    marginVertical: 24,
  },
  noticeText: { fontWeight: "600", color: "#4a5568", lineHeight: 24 },
  footerInfo: {
    alignItems: "center",
    paddingTop: 32,
    borderTopWidth: 2,
    borderTopColor: "#e2e8f0",
  },
  footerInfoText: { color: "#718096", fontSize: 14 },
  footer: { backgroundColor: "#2d3748", padding: 32, alignItems: "center" },
  copyright: { color: "#ffffff", fontSize: 14 },
});
